<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="Reqnroll.MsTest" Version="2.2.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPO.Correspondence.API\IPO.Correspondence.API.csproj" />
  </ItemGroup>

</Project>
