<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
    <PackageReference Include="IPO.Common.Infrastructure" Version="2.2.461532" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPO.Correspondence.Interfaces\IPO.Correspondence.Interfaces.csproj" />
    <ProjectReference Include="..\IPO.Correspondence.Models\IPO.Correspondence.Models.csproj" />
  </ItemGroup>

</Project>
